# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

<<<<<<< HEAD
name: Run automated tests
=======
name: Run tests on develop
>>>>>>> develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
<<<<<<< HEAD
        pip install py-make
    - name: Run tests
      run: |
=======
        pip install py-make flake8 flake8-html pylama requests
    - name: Run tests
      run: |
        export PYTHONPATH="./":${PYTHONPATH}
>>>>>>> develop
        pymake test
